mypet/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('index.urls')),
    path('',RedirectView.as_view(url='/index/', permanent=True)),
    path('user/', include('user.urls')),

]
urlpatterns += [
    path('home/', RedirectView.as_view(url='/index/', permanent=True)),
]

user/urls.py
from django.urls import path
from . import views
app_name = 'user'
urlpatterns = [
    path('signup/', views.signup, name= 'signup'),
    path('login/', views.login, name= 'login'),
    path('logout/', views.logout, name= 'logout'),
    
]

home/views.py
from django.shortcuts import render

def index(request):
    context={}

    login_session = request.session.get('login_session','')
    if login_session == '':
        context['login_session'] = False
    else:
        context['login_session'] =True

    return render(request, 'home/index.html', context)



def favorites(request):
    return render(request,'home/favorites.html')
def about(request):
    return render(request,'home/about.html')
def contact(request):
    return render(request,'home/contact.html')

home/templates/home/aa.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> MyPet Website</title>
    <link rel = "stylesheet" type="text/css" href="{% static 'css/aa.css' %}">
    <link rel = "stylesheet" type="text/css" href="{% static 'css/scroll.css' %}">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap');
    </style>
</head>
<body>

<div id="container">
    <header id = "header"> 
        <nav class ="menu">
            <ul>
                <li><a href = "{% url 'aa' %}" <b>Home</b></a></li>
                <li><a href = "{% url 'about' %}" <b>About</b></a></li>
                <li><a href = "{% url 'favorites' %}" <b>favorites</b></a></li>
                <li><a href = "{% url 'contact' %}" <b>Contact</b></a></li>
                {% if login_session %}
                    <li><a href="{% url 'user:logout' %}" >Logout</a></li>
                {% else %}
                    <li><a href="{% url 'user:signup' %}" >Signup</a></li>
                    <li><a href="{% url 'user:login' %}" class="login-btn">Login</a></li>
                {% endif %}
        </nav>
    </header> 
  <div class="list">
      <div class="one">
        <span class="profile"><img src="/static/img/jm.png" width="550px;" height="550px" alt=""/></span> 
        <h3><strong>Hello! I'm 몽자.</strong> <br>You can scroll down if you want to see me more!</h3>
      </div>
  </div>

  <div class="list">
      <div class ="two">
          <img class = "me" src ="/static/img/mmo.jpg" alt="" width="450px;" height="500px">
          <h3 class ="intext"> <strong>Who is 몽자?<br></strong><br><br>
            Hello! I'm 몽자. Welcome to my homepage.<br><br>
            
            I'm a female Poodle. 
            I'm 7 years old this year and <br>my birthday is on April 8th. <br>
            I'm very gentle and cute personality and <br>love my family very much.
            <br>
            I enjoy various hobbies and travels, <br>
            sharing them with people <br>through social media such as YouTube and Instagram.
            <br>
            <br>
            <br>
            </h3>
      </div>
  </div>
  
  <div class="list">
      <div class="three">
          <h1><br><br> 💕 💕 💕 </h1>
          <div class = "favorites">
              <div class="lists">
                  <img class = "list_img" src="/static/img/fri.jpg" alt="">
                  <p class = "list_text">모든 강아지와 친구에요 🐶</p>
              </div>

              <div class="lists">
                  <img class = "list_img" src="/static/img/food.jpg" alt="">
                  <p class = "list_text"> 음식을 좋아해요 🥘</p>
              </div>

              <div class="lists">
                  <img class = "list_img" src="/static/img/san.jpg" alt="">
                  <p class = "list_text"> 산책도 즐기고 🏃🏻‍♂️</p>
              </div>

              <div class="lists">
                  <img class = "list_img" src="/static/img/gong.jpg" alt="">
                  <p class = "list_text"> 공놀이도 좋아해요! 💕</p>
              </div>
          </div>
      </div>
  </div>

  <div class="list">
    <div class = "four">
        <img class = "contact_img" src ="/static/img/aaa.jpg">
        <a href="https://www.youtube.com/@MONGJA/featured" class="ct">Velog</a>
        <a href="https://instagram.com/mongja0408?igshid=NTc4MTIwNjQ2YQ==" class="ct">Insta</a>
        <a href="https://www.facebook.com/mongja0408" class="ct">Facebook</a>
    </div>
</div>
</div>
</body>